name:                zfsborgmeup
version:             0.1.0.0
github:              "dbalan/zfsborgmeup"
license:             BSD3
author:              "Dhananjay Balan"
maintainer:          "mail@dbalan.in"
copyright:           "2019 Dhananjay Balan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            scripts

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbalan/zfsborgmeup#readme>

default-extensions:
- OverloadedStrings
- DeriveGeneric

dependencies:
- base >= 4.7 && < 5
- time
- turtle
- text
- foldl
- split
- yaml
- bytestring
- xdg-basedir
- unliftio
- path-io
- path
- optparse-applicative

library:
  source-dirs: src

executables:
  zfsborgmeup:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zfsborgmeup

tests:
  zfsborgmeup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zfsborgmeup
    - hspec
