version: 2
jobs:
  build:
    docker:
    - image: haskell:8.6.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-work-{{ checksum "package.yaml" }}
      - run:
          name: Who am I?
          command: uname -a
      - run:
          name: Build
          command: stack build
      - run:
          name: Test
          command: stack test
      - save_cache:
          key: stack-work-{{ checksum "package.yaml" }}
          paths:
            - .stack-work
